### PR TITLE
add test texts to repo

### PR DESCRIPTION
**Pull request by Finnoscarmorgan**
Ten test texts for testing NER performance, have forked original repo please let me know if this is best way to collaborate.

### CODE REVIEW

**Comment by benfoley** [comment]
Is there a naming convention for the entire corpus? If so it would be good to review it and remove spaces and brackets etc to make them more compute-friendly (hyphens and underscores ok but no other punctuation in base names). Would be good to clean up the names even for these text texts.

**Comment by Finnoscarmorgan** [comment]
> Is there a naming convention for the entire corpus? If so it would be good to review it and remove spaces and brackets etc to make them more compute-friendly (hyphens and underscores ok but no other punctuation in base names). Would be good to clean up the names even for these text texts.

Are you referring to the filenames of text files? 
-First item in file name is unique Trove id
- Next three are the date of publication
- Next I believe is newspaper_id? (I need to check)
- Then chapter title
- Last number is unique article id (essentially chapter id)
Would it be simplest to replace all spaces with dashes?

**Comment by benfoley** [comment]
Thanks, it's good to have the naming documented. Yes, at least replace spaces with dashes or underlines. Also, remove () and other punctuation, either delete or replace with dashes or underlines too.

**Comment by Finnoscarmorgan** [comment]
> Thanks, it's good to have the naming documented. Yes, at least replace spaces with dashes or underlines. Also, remove () and other punctuation, either delete or replace with dashes or underlines too.

Thanks Ben, I will will just remove all unnecessary characters from test files manually to begin with.

**Comment by Finnoscarmorgan** [comment]
> 
Sorry Ben, I misunderstood, I will amend text filenames before they are merged into repo (sorry still figuring out some Git stuff).

**Comment by Finnoscarmorgan** [comment]
Have standardised filenames for processing

**Pull request merged**
